ALTER TABLE funded_challenges
  ADD COLUMN IF NOT EXISTS max_daily_profit_pct DECIMAL(5,2) NOT NULL DEFAULT 35.00,
  ADD COLUMN IF NOT EXISTS max_risk_per_trade_pct DECIMAL(5,2) NOT NULL DEFAULT 2.00,
  ADD COLUMN IF NOT EXISTS max_lot_size DECIMAL(8,2) NOT NULL DEFAULT 1.00;

ALTER TABLE challenge_accounts
  ADD COLUMN IF NOT EXISTS consistency_breached BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS risk_breached BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS max_observed_lot DECIMAL(8,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_observed_risk_pct DECIMAL(5,2) NOT NULL DEFAULT 0;

ALTER TABLE challenge_rule_snapshots
  ADD COLUMN IF NOT EXISTS max_daily_profit_pct DECIMAL(5,2) NOT NULL DEFAULT 35.00,
  ADD COLUMN IF NOT EXISTS max_risk_per_trade_pct DECIMAL(5,2) NOT NULL DEFAULT 2.00,
  ADD COLUMN IF NOT EXISTS max_lot_size DECIMAL(8,2) NOT NULL DEFAULT 1.00;

ALTER TABLE metric_snapshots
  ADD COLUMN IF NOT EXISTS max_observed_lot DECIMAL(8,2),
  ADD COLUMN IF NOT EXISTS max_observed_risk_pct DECIMAL(5,2);
